### ISSUE TITLE
Helm support for Confluent Kafka setups

### ISSUE THREAD

**Issue by arov00** [spoud/kafka-cost-control#283]
The existing [helm chart PR](https://github.com/spoud/kafka-cost-control/pull/282) sets up cost control for a Strimzi environment. It would be good if we could extend it to also support Kafka clusters that are not deployed using Strimzi. For example, the value file could look as follows:

```yaml
kafkaType: confluent

# this is not active (and could be omitted) because kafkaType is confluent
strimzi:
  clusterName: my-cluster
  bootstrapServer: my-cluster-kafka-bootstrap:9094
  # more strimzi settings here...

# If confluent is enabled, the chart generates a telegraf config that queries the confluent metrics api + some other confluent-specific things are set up (and strimzi-specific things are deactivated)
confluent:
  bootstrapServer: my-cluster-kafka-bootstrap:9094
  # more confluent settings here...
```

If Confluent is enabled, then we are no longer able to rely on Strimzi's `KafkaConnect` and `KafkaConnector` resources for sinking metrics to timescaleDB. In this case, the setup from Kustomize should be used (spin up a Kafka Connect deployment, instead of using custom resources).
