### ISSUE TITLE
Add schema registry authentication options

### ISSUE THREAD

**Issue by arov00** [spoud/kafka-cost-control#284]
Currently, the Helm chart supports only the most basic schema registry configuration (only setting the schema registry URL is supported). This is fine for schema registries that are not secured in any way, but a better solution is needed for secured deployments.

Here are the components that rely on schema registry:
- Strimzi Context Operator
- Aggregator
- Kafka Connect

Ideally, the `values.yaml` would be extended as follows:

```yaml
schemaRegistry:
    url: http://schema-registry:8080/apis/ccompat/v7
    basicAuthCredentials:
      secretName: mysecret
      usernameKey: user
      passwordKey: password
```

Then those values should be plugged into the template whenever needed.
